services:
  clinmesh:
    environment:
      CLINMESH_SYNTHEA_PROVIDER_URL: http://synthea-provider:8080

  synthea-provider:
    extends:
      file: compose.synthea-provider.yaml
      service: synthea-provider
