services:
  clinmesh:
    environment:
      CLINMESH_SYNTHEA_PROVIDER_URL: http://synthea-provider:51878

  cn-health-localizer:
    extends:
      file: compose.synthea-provider.yaml
      service: cn-health-localizer

  synthea-provider:
    extends:
      file: compose.synthea-provider.yaml
      service: synthea-provider
