import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import tailwindcss from '@tailwindcss/vite'
import postcss from 'postcss'
import selectorParser from 'postcss-selector-parser'
import { build } from 'vite'

const moduleDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(moduleDirectory, '..', '..', '..')
const entry = join(moduleDirectory, 'client', 'styles-entry.ts')
const generatedModule = join(moduleDirectory, 'client', 'styles.generated.ts')
const query = '?dsh-surface'

const result = await build({
  build: {
    cssCodeSplit: false,
    lib: { entry, fileName: 'styles-entry', formats: ['es'] },
    minify: true,
    write: false,
  },
  configFile: false,
  logLevel: 'silent',
  plugins: [{
    enforce: 'pre',
    name: 'clinmesh-dsh-shadow-styles',
    async load(id) {
      if (!id.endsWith(query)) return null
      const sourcePath = id.slice(0, -query.length)
      this.addWatchFile(sourcePath)
      return readFile(sourcePath, 'utf8')
    },
  }, tailwindcss()],
  root: repositoryRoot,
})

const outputs = (Array.isArray(result) ? result : [result]).flatMap(output => {
  if (!('output' in output)) throw new Error('Unexpected Vite watcher while building styles')
  return output.output
})
const cssAssets = outputs.filter(output => output.type === 'asset' && output.fileName.endsWith('.css'))
const unsupported = outputs.filter(output => output.type === 'asset' && !output.fileName.endsWith('.css'))
if (cssAssets.length !== 1 || unsupported.length > 0) {
  throw new Error('DSH style build must emit exactly one CSS asset')
}
const asset = cssAssets[0]
if (asset === undefined || asset.type !== 'asset') throw new Error('Missing DSH stylesheet')
const source = typeof asset.source === 'string' ? asset.source : Buffer.from(asset.source).toString()
const stylesheet = postcss.parse(source)

stylesheet.walkRules(rule => {
  if (rule.selector === undefined) return
  rule.selector = selectorParser(selectors => {
    selectors.walkPseudos(pseudo => {
      if (pseudo.value === ':root') {
        pseudo.replaceWith(selectorParser.className({ value: 'clinmesh-web-root' }))
      }
    })
    selectors.walkTags(tag => {
      if (tag.value === 'html' || tag.value === 'body') {
        tag.replaceWith(selectorParser.className({ value: 'clinmesh-web-root' }))
      }
    })
    selectors.walkIds(id => {
      if (id.value === 'root') {
        id.replaceWith(selectorParser.className({ value: 'clinmesh-web-root' }))
      }
    })
  }).processSync(rule.selector)
})

stylesheet.walkAtRules('media', atRule => {
  if (/^\(width\s*>=\s*[^)]+\)$/.test(atRule.params)) {
    atRule.name = 'container'
    atRule.params = `dsh-react-surface-content ${atRule.params}`
  }
})

stylesheet.walkDecls(declaration => {
  declaration.value = declaration.value.replaceAll('100svh', '100%')
})

await writeFile(
  generatedModule,
  `/** Generated by build-styles.ts. */\nexport const clinMeshStyles = ${JSON.stringify(stylesheet.toString())};\n`,
  'utf8',
)
