import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildSurfaceStyles } from './surface-styles.ts'

const moduleDirectory = dirname(fileURLToPath(import.meta.url))
const generatedModule = join(moduleDirectory, 'client', 'styles.generated.ts')

await writeFile(
  generatedModule,
  `/** Generated by build-styles.ts. */\nexport const clinMeshStyles = ${JSON.stringify(await buildSurfaceStyles())};\n`,
  'utf8',
)
