import { referenceMedicationProductSchema } from '@clinmesh/contracts/reference-data'

export const syntheticNhsaMedicationProductSnapshot = referenceMedicationProductSchema.array().parse([
  {
    approvalNumber: 'CM-APPROVAL-ACETAMINOPHEN',
    brandName: null,
    code: 'CM-NHSA-PRODUCT-ACETAMINOPHEN',
    dosageForm: '片剂',
    genericName: '对乙酰氨基酚片',
    id: 'nhsa-medication-product:nhsa-medication-products-2026-08-07:CM-NHSA-PRODUCT-ACETAMINOPHEN',
    manufacturer: '仁和仿真制药一厂',
    packageDescription: '20片/盒',
    sourceLocator: 'nhsa-medication-products.csv:2',
    status: 'active',
    strength: '500 mg',
    system: 'urn:clinmesh:reference:nhsa-medication-product',
    version: 'nhsa-medication-products-2026-08-07',
  },
  {
    approvalNumber: 'CM-APPROVAL-METFORMIN',
    brandName: null,
    code: 'CM-NHSA-PRODUCT-METFORMIN',
    dosageForm: '片剂',
    genericName: '盐酸二甲双胍片',
    id: 'nhsa-medication-product:nhsa-medication-products-2026-08-07:CM-NHSA-PRODUCT-METFORMIN',
    manufacturer: '仁和仿真制药二厂',
    packageDescription: '60片/盒',
    sourceLocator: 'nhsa-medication-products.csv:3',
    status: 'active',
    strength: '500 mg',
    system: 'urn:clinmesh:reference:nhsa-medication-product',
    version: 'nhsa-medication-products-2026-08-07',
  },
  {
    approvalNumber: 'CM-APPROVAL-AMLODIPINE',
    brandName: null,
    code: 'CM-NHSA-PRODUCT-AMLODIPINE',
    dosageForm: '片剂',
    genericName: '苯磺酸氨氯地平片',
    id: 'nhsa-medication-product:nhsa-medication-products-2026-08-07:CM-NHSA-PRODUCT-AMLODIPINE',
    manufacturer: '仁和仿真制药三厂',
    packageDescription: '30片/盒',
    sourceLocator: 'nhsa-medication-products.csv:4',
    status: 'active',
    strength: '5 mg',
    system: 'urn:clinmesh:reference:nhsa-medication-product',
    version: 'nhsa-medication-products-2026-08-07',
  },
])
