export const syntheaR4ResourceTypes = [
  'AllergyIntolerance',
  'CarePlan',
  'CareTeam',
  'Claim',
  'Condition',
  'Coverage',
  'Device',
  'DiagnosticReport',
  'Encounter',
  'ExplanationOfBenefit',
  'Goal',
  'ImagingStudy',
  'Immunization',
  'Location',
  'Medication',
  'MedicationAdministration',
  'MedicationRequest',
  'Observation',
  'Organization',
  'Patient',
  'Practitioner',
  'Procedure',
  'Provenance',
  'SupplyDelivery',
] as const
